# Generated by Django 3.2.4 on 2022-12-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_social_twiter_profile_social_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='description',
            new_name='detail',
        ),
    ]
