# Generated by Django 3.2.4 on 2022-12-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_description_skill_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='detail',
            new_name='detdescriptionail',
        ),
    ]
