# Generated by Django 3.2.4 on 2022-12-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_detail_skill_detdescriptionail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='detdescriptionail',
            new_name='description',
        ),
    ]
