# Generated by Django 3.2.4 on 2022-12-31 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_detdescriptionail_skill_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_linkdin',
            new_name='social_linkedin',
        ),
    ]
