# Generated by Django 3.2.4 on 2022-12-10 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_content_course_registration_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='courseid',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='studentid',
        ),
        migrations.DeleteModel(
            name='content',
        ),
        migrations.DeleteModel(
            name='course',
        ),
        migrations.DeleteModel(
            name='registration',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
